"""Convert content_chunks.embedding from JSONB to vector(384) and add HNSW index.

Revision ID: 001
Revises: 
Create Date: 2026-06-02

IMPORTANT: This migration drops and recreates the embedding column.
All existing embeddings will be lost and must be regenerated by running:
    python -m edu_curator.cli map-topic
Generated content (topic_content, topic_knowledge, fact_extractions) is NOT affected.
"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # Step 1: Enable pgvector extension (idempotent)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Step 2: Drop old JSONB embedding column
    op.execute("ALTER TABLE content_chunks DROP COLUMN IF EXISTS embedding")

    # Step 3: Add proper vector(384) column
    op.execute("ALTER TABLE content_chunks ADD COLUMN embedding vector(384)")

    # Step 4: Create HNSW index for approximate nearest-neighbour search
    # CONCURRENTLY = zero downtime on production (no table lock)
    # m=16, ef_construction=64 = good default quality/speed balance
    op.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_chunks_embedding_hnsw
        ON content_chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # Step 5: Set ef_search for query-time quality (persisted per-session default)
    # ef_search=40 is the default; raise to 100 for better recall at scale
    op.execute("ALTER DATABASE postgres SET hnsw.ef_search = 40")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_chunks_embedding_hnsw")
    op.execute("ALTER TABLE content_chunks DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE content_chunks ADD COLUMN embedding JSONB")
